{ $jrsoftware: tb2k/Source/TB2Ver.inc,v 1.11 2008/09/13 21:06:45 jr Exp $ }

{$IFNDEF FPC}
  {$MESSAGE ERROR 'Use FPC!'}
{$ENDIF}

{$IFNDEF LCL}
  {$MESSAGE ERROR 'Use LCL!'}
{$ENDIF}

{$DEFINE JR_D4}  { then it must be at least Delphi 4 or C++Builder 4 }
{$DEFINE JR_D5}  { then it must be at least Delphi 5 or C++Builder 5 }
{$DEFINE JR_D5}  { then it must be at least Delphi 5 or C++Builder 5 }
{$DEFINE JR_D6}  { then it must be at least Delphi 6 or C++Builder 6 }
{$DEFINE JR_D7}  { then it must be at least Delphi 7 }
{$DEFINE JR_D8}  { then it must be at least Delphi 8 }

{$ALIGN ON}
{$BOOLEVAL OFF}
{$LONGSTRINGS ON}
{$TYPEDADDRESS OFF}
{$WRITEABLECONST ON}

